runtime: python311
env: standard
entrypoint: python3 -m src.main

handlers:
- url: /.*
  script: auto

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1

#inbound_services:
#  - warmup
